# Read the documentation before using the `docker-compose.yml` file:
# https://docs.searxng.org/admin/installation-docker.html

name: searxng

services:
  searxng-warp:
    container_name: searxng-warp
    image: monius/docker-warp-socks:latest
    privileged: true
    restart: always
    stop_grace_period: 1s
    ports:
      - "9091:9091"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1

  searxng-tor:
    container_name: searxng-tor
    image: peterdavehello/tor-socks-proxy:latest
    restart: always
    command: tor -f /etc/tor/torrc --MaxCircuitDirtiness 120 --NewCircuitPeriod 30 --CircuitBuildTimeout 10

  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      # - ${SEARXNG_HOST:+${SEARXNG_HOST}:}${SEARXNG_PORT:-8080}:${SEARXNG_PORT:-8080}
      - "8080:8080"
    env_file: ./.env
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - core-data:/var/cache/searxng/
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}:${SEARXNG_PORT}/${SEARXNG_PATH}/
      - SEARXNG_SECRET=${SEARXNG_SECRET}

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - valkey-data:/data/

  caddy:
    image: caddy:2-alpine
    container_name: searxng-caddy
    restart: always
    ports:
      - "80:80"
      - "${SEARXNG_PORT}:${SEARXNG_PORT}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME}
      - SEARXNG_PORT=${SEARXNG_PORT}
      - SEARXNG_PATH=${SEARXNG_PATH}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

volumes:
  core-data:
  valkey-data:
  caddy_data:
  caddy_config:
