use_default_settings:
  engines:
    keep_only:
      # General
      - brave
      - bing
      - google
      - duckduckgo
      - mojeek
      - qwant
      - startpage
      - wikipedia
      - wikidata

      # Images
      # - mojeek images
      - startpage images
      - google images
      - bing images
      - duckduckgo images
      # - devicons
      # - lucide
      - deviantart

      # Video
      - youtube
      - vimeo
      - mediawiki

      # IT
      - github
      - mdn
      - arch linux wiki
      - stackoverflow
      - mediawiki
      - nixos wiki

      # Files
      # - piratebay
      # - bt4g
      # - kickass

      # News
      # - startpage news
      # - wikinews
      # - brave.news
      # - google news
      # - qwant news
      # - yahoo news

search:
  favicon_resolver: "allesedv"

  ban_time_on_fail: 5
  max_ban_time_on_fail: 30

  suspended_times:
    SearxEngineAccessDenied: 300
    SearxEngineCaptcha: 600
    SearxEngineTooManyRequests: 300
    cf_SearxEngineCaptcha: 900
    cf_SearxEngineAccessDenied: 600
    recaptcha_SearxEngineCaptcha: 900

ui:
  results_on_new_tab: true
  url_formatting: host

categories_as_tabs:
  general:
  images:
  videos:
  it:
  # news:
  # science:
  # files:
  # social media:

# proxies: socks5h://searxng-tor:9150
engines:
  - name: mojeek
    shortcut: mjk
    engine: mojeek
    disabled: false

  - name: mojeek images
    shortcut: mjkimg
    engine: mojeek
    categories: [images, web]
    search_type: images
    disabled: true

  - name: duckduckgo images
    shortcut: ddi
    engine: duckduckgo_extra
    categories: [images, web]
    ddg_category: images
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: qwant
    qwant_categ: web
    engine: qwant
    shortcut: qw
    categories: [general, web]
    disabled: false

  - name: nixos wiki
    engine: mediawiki
    shortcut: nixw
    base_url: https://wiki.nixos.org/
    search_type: text
    disabled: false
    categories: [it, software wikis]
